aws:
  region: "us-east-1"
  bedrock:
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"  # Claude 3 Haiku - 20 req/min rate limit
    max_tokens: 4000
    temperature: 0.1

processing:
  input_folder: "walkthroughs"
  output_filename: "summary.md"
  
summary:
  style: "detailed"  # Options: brief, comprehensive, detailed
  include_timestamps: true
  include_participants: true
  include_action_items: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
