aws:
  region: "us-west-2"
  bedrock:
    model_id: "anthropic.claude-3-haiku-20240307-v1:0"  # Claude 3 Haiku - 20 req/min rate limit
    # model_id: "openai.gpt-oss-120b-1:0"
    # model_id: "anthropic.claude-sonnet-4-20250514-v1:0"
    # model_id: "anthropic.claude-opus-4-1-20250805-v1:0"
    # model_id: "anthropic.claude-opus-4-20250514-v1:0"
    # model_id: "openai.gpt-oss-20b-1:0"
    max_tokens: 4000
    temperature: 0.1

processing:
  input_folder: "inputs"
  output_folder: "outputs"
  
  # Filename formats - use placeholders: {folder_name}, {timestamp}, {date}
  individual_summary_filename: "{folder_name}_summary.md"
  global_summary_filename: "global_summary.md"
  
  # Input file patterns to look for (VTT files)
  input_file_patterns: ["*.vtt"]
  
summary:
  style: "comprehensive"  # Options: brief, comprehensive, detailed
  include_timestamps: true
  include_participants: true
  include_action_items: true

pdf:
  enabled: true                           # Enable/disable PDF generation
  filename: "complete_summary_report_{date}.pdf"  # PDF filename template
  title: "Meeting Summary Report"         # PDF document title
  include_table_of_contents: true         # Include TOC in PDF
  include_keyframes: true                 # Include keyframes in PDF
  page_size: "A4"                        # Page size (A4, Letter, etc.)
  font_size: 11                          # Base font size

keyframes:
  enabled: true              # Enable/disable keyframe extraction globally
  max_frames: 10              # Maximum keyframes per video (can be overridden by CLI)
  min_relevance_score: 0.3   # Minimum score threshold for keyframe candidates
  image_max_width: 1200      # Maximum width for optimized keyframe images (px)
  image_quality: 100          # Image quality for optimization (0-100)
  
  # Intelligent delay settings (in seconds)
  # These delays help capture the actual moment rather than just announcements
  # Adjust based on your typical meeting patterns
  delays:
    screen_sharing: 20.0        # "I will share my screen" -> wait for actual sharing
    screen_sharing_immediate: 1.0  # "I'm sharing my screen" -> already happening  
    demonstrations: 5.0        # "Let me show you" -> wait for demo to start
    technical: 3.0            # Technical discussions -> small delay for context
    transitions: 5.0          # "Moving on to" -> wait for transition to complete
    important: 1.0            # Important points -> small delay for emphasis
    questions: 1.0            # Q&A moments -> wait for response context

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Prompt Templates for Model Interactions
prompts:
  # Individual meeting summary prompt template
  individual_summary:
    # Main instruction template with placeholders
    instruction: "Please analyze the following meeting transcript and create a {summary_style} summary."
    
    # Requirements that can be conditionally included
    requirements:
      participants: "- **Participants**: List of people who spoke during the meeting"
      main_topics: "- **Main Topics**: Key subjects discussed during the meeting"
      key_points: "- **Key Points**: Important information, decisions, and insights shared"
      technical_details: "- **Technical Details**: Any technical concepts, architectures, or implementations discussed"
      action_items: "- **Action Items**: Tasks, next steps, or follow-up items mentioned"
      decisions: "- **Decisions Made**: Any concrete decisions or conclusions reached"
      questions_issues: "- **Questions/Issues Raised**: Important questions or problems discussed"
      timeline: "- **Timeline**: Reference key moments with approximate timestamps when significant topics were discussed"
    
    # Formatting instructions
    format_instructions: |
      Please format the summary in clear Markdown with appropriate headers and bullet points.
      Focus on technical accuracy and ensure all important information is captured.
    
    # Template structure
    template: |
      {instruction}
      
      Your summary should include:
      {requirements}
      
      {format_instructions}
      
      {context_info}**Transcript:**
      {transcript}
  
  # Global summary prompt template
  global_summary:
    # Main instruction for global analysis
    instruction: "Please analyze the following series of technical walkthrough meetings and create a comprehensive global summary."
    
    # Required sections for global summary
    required_sections:
      - "- **Executive Summary**: High-level overview of the entire walkthrough series"
      - "- **Meeting Series Overview**: List of all meetings with key details"
      - "- **Cross-Meeting Themes**: Common themes and patterns across all sessions"
      - "- **Technical Architecture Overview**: Overall technical landscape discussed"
      - "- **Key Stakeholders**: People involved across multiple sessions"
      - "- **Strategic Initiatives**: Major projects and initiatives identified"
      - "- **Technology Stack**: Technologies, platforms, and tools discussed"
      - "- **Migration & Transformation**: Any migration or modernization efforts"
      - "- **Outstanding Issues**: Common problems and challenges across meetings"
      - "- **Action Items Summary**: Consolidated action items and next steps"
      - "- **Recommendations**: Strategic recommendations based on all meetings"
    
    # Formatting instructions for global summary
    format_instructions: |
      Format the output in clear Markdown with appropriate headers and bullet points.
      Focus on strategic insights and cross-meeting connections rather than individual meeting details.
    
    # Template structure
    template: |
      {instruction}
      
      You should provide:
      {required_sections}
      
      {format_instructions}
      
      **Meeting Series Overview:**
      {meetings_overview}
      
      **Individual Meeting Summaries for Analysis:**
      {combined_summaries}
